### ISSUE TITLE
[C4GT] Pdf text parsing( + Dictionary Augmented Transformers ) 

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#81]
### Features to be implemented

Dictionary Augmented Translation Models is an approach in natural language processing (NLP) that aims to enhance translation models by incorporating a dictionary of correct translations. The goal is to ensure that the translated output contains the translated words from a supplied dictionary, especially for words where the translation is known with certainty. This project serves as a wrapper over existing translation transformers like Fairseq to implement this approach.

### How it works
The dictionary augmented translation models typically involve the following components:

#### Data Preparation
Collecting and organizing a dictionary of correct translations for specific words or phrases in the input language ( assume this is provided by the user as the input)

#### Integration with Translation Transformer
Developing a wrapper or interface to integrate the dictionary with an existing translation transformer, such as Fairseq.

#### Dictionary Lookup
During the translation process, identifying words or phrases from the input text that match the entries in the dictionary.

#### Word Replacement
Replacing the translated output of the identified words or phrases with their corresponding translations from the dictionary ( for this one has to be able to identify which words in the input correspond to which words in the output)

#### Translation Transformer Execution
Executing the translation using the underlying translation transformer to generate the initial translation output.

#### Replacement with Dictionary Translations
Replacing the identified words or phrases in the initial translation output with their correct translations from the dictionary.

#### Deployment
Deploying the dictionary augmented translation model as part of the AI-tools package, enabling dockerization and access through an API setup.

#### Complexity  
Easy

#### Skills Required 
Python, NLP, Fairseq or similar translation transformer frameworks

#### Name of Mentors:        
@GautamR-Samagra 
### Project size
8 Weeks

### Product Set Up
See the setup [here](https://github.com/Samagra-Development/ai-tools)

### Acceptance Criteria 
- [ ] Unit Test Cases

### Milestone
Every major improvement in translation accuracy achieved using the dictionary augmentation is considered a milestone.

### Reference
Provide relevant references or articles about dictionary augmented translation models.

# C4GT
This issue is nominated for Code for GovTech (C4GT) 2023 edition. 
C4GT is India's first annual coding program to create a community that can build and contribute to global [Digital Public Goods](https://www.codeforgovtech.in/digitalpublicgoods). If you want to use Open Source GovTech to create impact, then this is the opportunity for you! More about C4GT here: https://codeforgovtech.in/

-----------------------------------------------------------------------------------------------------------------------------------------

The scope of this ticket has now expanded to make it the 'input' part of 'FAQ bot'. 
The FAQ bot allows a user to be able to provide content input in the form on csvs, free text, pdfs, audio, video and the bot is able to add it to a 'Content DB'. The user is then able to interact with the bot via text/speech on related content and the bot is able to identify relevant content using RAG techniques and be able to be able to respond to the user in a conversational manner.  

This ticket covers the content input part of the bot. It includes the following tasks in its scope:  
 
- [ ] Maintain a test suite of Odia translations :  https://github.com/Samagra-Development/ai-tools/issues/162
- [ ] Create a POC for verifying translations after dictionary modifications: https://github.com/Samagra-Development/ai-tools/issues/163
- [ ] Being able to able to detect text boundary in pdfs :  https://github.com/Samagra-Development/ai-tools/issues/164
- [x] #185
- [ ] Being able to identify tables and extract information from texts
- [ ] Extracting transcripts from videos/audios :  https://github.com/Samagra-Development/ai-tools/issues/165
- [x] #173
- [ ] Packaging all the above work to integrate with ai-tools

**Comment by ChakshuGautam** [comment]
Hey can't assign before deadline. Please raise a PR directly.

**Comment by shievamkr** [comment]
I would like to contribute to this project and looking forward to join through C4GT.

**Comment by vroy651** [comment]
how to proceed further with this given information, and what will have to do next?

**Comment by AnanyaSDhar** [comment]
I'm interested in this project. I have prior experience with NLP. Could you please guide how to start with the project?

**Comment by Anindita1709** [comment]
I would like to work on this issue. Can you please provide more details to set up?

**Comment by danishraza0912** [comment]
Hey, I want to contribute to this project. The setup link does not exist. Pls see if you can fix it.

**Comment by ChakshuGautam** [comment]
Updated Setup link.

**Comment by GautamR-Samagra** [comment]
Raised a PR here: 
https://github.com/Samagra-Development/ai-tools/pull/89

The above is an inital setup for replacing the translated words of Azure Odia to English translate with the correct translation for a dictionary of odia words.

**Comment by shreyasg33** [comment]
Hey, I would like to work on this project , looking forward to join through C4GT. Can u pls provide further details to join this program....

**Comment by TakshPanchal** [comment]
> Hey, I would like to work on this project , looking forward to join through C4GT. Can u pls provide further details to join this program....

Visit this [website](https://www.codeforgovtech.in/) and join the discord server.

**Comment by shrivastava95** [comment]
Hello guys, a good amount of work has been done in this direction so the scope of this project is expanding. Refer to [this repository](https://github.com/shrivastava95/odia-dictionary/issues) being maintained by chakshu to get an idea of the new scope and all the new issues associated.

**Comment by Charan-Nandarapu** [comment]
I would like to contribute to this project and looking forward to join through C4GT.

**Comment by Anusha29-creator** [comment]
I would like to contribute to this project.

**Comment by nidhi27sahu** [comment]
I'm interested in this project. I have experience in NLP. Could you please guide how to start with the project?

**Comment by Ritajamaitra** [comment]
@ChakshuGautam 
Dear Sir,

My name is Ritaja Maitra, studying B.Tech[Computer Science Engineering] penultimate year at Institute of Engineering and Management,Kolkata.
I am writing this regarding an internship opportunity in your esteemed project as a part of my education.

I wanted to be sure to reach out as I am highly interested in this opportunity, and I believe that my relevant skills would be a good fit for this position.

To that end, I am convinced that I will be able to push boundaries by thinking out of the box and explore the endless opportunities this industry presents. Kindly give me an opportunity to send my proposal draft for review before final submission.
Looking forward to your response

Warmest regards
Ritaja Maitra

**Comment by Abhinavarya7** [comment]
@ChakshuGautam 
Hello sir, I am Abhinav Arya 3rd year Bio-Engineering student, I would like to contribute to this project. Also eager to learn new things.

**Comment by Mac16661** [comment]
Dear sir,

I am Subhodip Ghosh, a student at Vellore Institute of Technology, currently pursuing a Masters of Computer Application course. I am extremely passionate about software development and have acquired experience in a wide range of technologies, including Machine Learning, Python, Java, JavaScript, C, C++ programming, full-stack web development, and AWS. Moreover, I have hands-on experience in developing NLP systems using the BERT transformer. I am highly interested in contributing to this project and I am enthusiastic about acquiring knowledge in emerging technologies..

I would be truly grateful if you could provide me with this wonderful opportunity.

Best regards,
Subhodip Ghosh

**Comment by tushar2242** [comment]
Hi, I'm interested in this project. I have experience in React Js ,Python , NLP .
Could you please guide how to start with the project?

**Comment by Samhitha310** [comment]
I'm interested in this project. I have learned python and i know a bit about NLP. could you please guide me in it!!!
